name: Build RNotebooks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Build notebook pages
      uses: addnab/docker-run-action@v3
      with:
        image: ebardelli/rethinking
        options: -v ${{ github.workspace }}:/work
      run: |
        Rscript notebooks/compile.R
        mkdir build
        mv notebooks/*.html build/

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./build
        keep_files: true
        commit_message: ${{ github.event.head_commit.message }}
